src/Entity/Bien.php
<?php

namespace App\Entity;

use App\Repository\BienRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BienRepository::class)]
class Bien
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255,nullable: true)]
    private ?string $reference = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $localisation = null;

    #[ORM\Column(length: 255)]
    private ?string $surface = null;

    #[ORM\Column]
    private ?int $prix = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\ManyToOne(inversedBy: 'biens')]
    private ?Categorie $id_categorie = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $image = null;

    public function __toString(): string
    {
       return $this->titre;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLocalisation(): ?int
    {
        return $this->localisation;
    }

    public function setLocalisation(int $localisation): self
    {
        $this->localisation = $localisation;

        return $this;
    }

    public function getSurface(): ?string
    {
        return $this->surface;
    }

    public function setSurface(string $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getIdCategorie(): ?Categorie
    {
        return $this->id_categorie;
    }

    public function setIdCategorie(?Categorie $id_categorie): self
    {
        $this->id_categorie = $id_categorie;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Controller/BienDisponibleController.php
<?php

namespace App\Controller;

use App\Entity\Bien;
use App\Repository\BienRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Doctrine\Persistence\ManagerRegistry;

class BienDisponibleController extends AbstractController
{

    public function __construct(ManagerRegistry $registry)
    {
        $this->doctrine = $registry;
    }

    #[Route('/bien/{id}', name: 'app_bien_disponibleById')]
    public function index(String $id, EntityManagerInterface $em): Response
    {

        //Trois biens de façon aléatoire
        $em = $this->doctrine->getManager();
        //On récupère les biens de la bdd
        $biens = $em->getRepository(Bien::class)->findAll();
        //On mélange les biens
        shuffle($biens);
        //On récupère les 3 premiers biens
        $randomBiens = array_slice($biens, 0, 3);

        //On récupère le bien correspondant à l'id
        $bien = $em->getRepository(Bien::class)->findBy(['id' => $id]);
        return $this->render('bien_disponible/index.html.twig', [
            'controller_name' => 'BienDisponibleController',
            'randomBiens' => $randomBiens,
            'bien' => $bien[0]
        ]);
    }
    #[Route('/bien', name: 'app_bien_all')]
    public function indexbis(EntityManagerInterface $em): Response
    {

        $bien = $em->getRepository(Bien::class)->findAll();
        return $this->render('bien_disponible/all.html.twig', [
            'biens' => $bien
        ]);
    }
}

templates/bien_disponible/all.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="{{ asset('style/annonce.css') }}"/>
	<link rel="stylesheet" href="{{ asset('style/bien.css') }}"/>
{% endblock %}

{% block javascripts %}
	<script src="{{ asset('js/bien.js') }}"></script>
{% endblock %}


{% block body %}
	<h2>Tous les biens disponible par notre agence</h2>
	<div class="nosBiens">
		{% for bien in biens %}
			<a href="{{ path('app_bien_disponibleById', {id: bien.id}) }}">
				<div class="contenaire">
					<div class="bien">
						{% if bien.reference != null %}
							<img src="/images/photo/{{ bien.reference }}.jpg" alt="Photo du bien présenté" onerror="this.src='/images/photo/noPhoto.jpg'" class="bienImage"/>
						{% else %}
							<img src="/uploads/images/{{ bien.image }}" alt="Photo du bien présenté" onerror="this.src='/images/photo/noPhoto.jpg'" class="bienImage"/>
						{% endif %}
						<a href="{{ path('app_admin_new', {id: bien.id}) }}" class="favorite-button">
							<img src="/images/logo/favicon.png" alt="Bouton favoris" class="favorite-button__image"/>
						</a>
						<div class="bienInfos">
							<h3 class="bienTitre">
								{{ bien.titre|slice(0, 30)|raw }}...
							</h3>
							<p class="bienPrix">
								{{ bien.prix }}
								€
							</p>
							<p class="bienCodePostal">
								{{ bien.localisation }}
							</p>
							<div>
								<img src="/images/logo/{{ bien.idCategorie }}.png" onerror="this.src='/images/photo/noPhoto.jpg'" alt="{{ bien.idCategorie }}" width="21" height="21" class="bienTypeImage"/>
								<p class="bienType">
									{{ bien.idCategorie }}
								</p>
							</div>
						</div>
					</div>
				</div>
			</a>
		{% endfor %}
	</div>
	<br><br>
	<div>
		<h2>
			Vous ne trouvez pas le bien parfait à votre goût ?
		</h2>
		<br>
		<form action="{{ path('app_contact') }}" method="post">
			<button type="submit" class="buttonContact">Me contacter dès l'arrivée d'un bien</button>
		</form>
		<br>
		<form action="{{ path('app_search') }}" method="post">
			<button type="submit" class="buttonContact">Chercher un autre bien avec des critères</button>
		</form>
	</div>


{% endblock %}

templates/bien_disponible/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('style/bienDisponible.css') }}"/>
	<link rel="stylesheet" href="{{ asset('style/bien.css') }}"/>
{% endblock %}

{% block title %}Hello BienDisponibleController!
{% endblock %}

{% block javascripts %}
	<script src="{{ asset('js/bien.js') }}"></script>
{% endblock %}

{% block body %}
	<h2>
		{{ bien.titre}}
		|
		{{ bien.type }}</h2>
	<section>
		<div>
			{% if bien.reference != null %}
				<img src="/images/photo/{{ bien.reference }}.jpg" alt="Photo du bien présenté" onerror="this.src='/images/photo/noPhoto.jpg'" class="bienImage"/>
			{% else %}
				<img src="/uploads/images/{{ bien.image }}" alt="Photo du bien présenté" onerror="this.src='/images/photo/noPhoto.jpg'" class="bienImage"/>
			{% endif %}
			<div class="bienDispoDescription">
				<h3>
					Type de bien
				</h3>
				<p>
					{{ bien.idCategorie }}
				</p>
				<h3>
					Surface du bien</h3>
				<p>
					{{ bien.surface }}
					m²
				</p>
				<h3>
					Localisation du bien
				</h3>
				<p>
					{{ bien.localisation }}
				</p>
				<h3>
					Prix du bien
				</h3>
				<p>
					{{ bien.prix }}
					€
				</p>
				<form action="{{ path('app_admin_new', {id: bien.id}) }}" method="post">
					<button type="submit" class="buttonFavoris">Ajouter en favoris</button>
				</form>
			</div>
		</div>
		<div>
			<h3>
				Description du bien
			</h3>
			<p>
				{{ bien.description }}
			</p>
		</div>
	</section>

	<hr/>

	<h2>
		Peut aussi vous intéresser
	</h2>
	<div class="nosBiens">
		{% for bien in randomBiens %}
			<a href="{{ path('app_bien_disponibleById', {id: bien.id}) }}">
				<div class="contenaire">
					<div class="bien">
						<img src="/images/photo/{{ bien.reference }}.jpg" alt="Photo du bien présenté" onerror="this.src='/images/photo/noPhoto.jpg'" class="bienImage"/>
						<a href="{{ path('app_admin_new', {id: bien.id}) }}" class="favorite-button">
							<img src="/images/logo/favicon.png" alt="Bouton favoris" class="favorite-button__image"/>
						</a>
						<div class="bienInfos">
							<h3 class="bienTitre">
								{{ bien.titre|slice(0, 30)|raw }}...
							</h3>
							<p class="bienPrix">
								{{ bien.prix }}
								€
							</p>
							<p class="bienCodePostal">
								{{ bien.localisation }}
							</p>
							<div>
								<img src="/images/logo/{{ bien.idCategorie }}.png" onerror="this.src='/images/photo/noPhoto.jpg'" alt="{{ bien.idCategorie }}" width="21" height="21" class="bienTypeImage"/>
								<p class="bienType">
									{{ bien.type }}
								</p>
							</div>
						</div>
					</div>
				</div>
			</a>
		{% endfor %}
	{% endblock %}